---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: python-tls
spec:
  secretName: python-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - python.devopsisfun.com
