---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-devopsisfun-com
  namespace: default
spec:
  secretName: nginx-devopsisfun-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "nginx.devopsisfun.com"
  dnsNames:
  - "nginx.devopsisfun.com"
